version: 2

sphinx:
  configuration: docs/conf.py

build:
  os: ubuntu-20.04
  tools:
    python: "3.10"
  commands:
    - pwd

python:
  install:
    - requirements: requirements.txt
    - method: pip
      path: .